kind: Service
apiVersion: v1
metadata:
  name: code-nfs
  namespace: blog
  labels:
    app: ghost
    type: nfs-storage
    content: code
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    app: ghost
    type: nfs-storage
    content: code